dump: false
fields:
    class: 'Combination'
    columns:
        id:
          type: increment
        id_product:
          relation: Product
          generate_all: true
        reference:
          value: ''
        supplier_reference:
          value: ''
        ean13:
          type: ean13
        upc:
          type: ean8
        wholesale_price:
          value: 0
        price:
          value: 0
        ecotax:
          value: 0
        quantity:
          type: numberBetween
          args:
            - 1
            - 100
        weight:
          value: 0
        unit_price_impact:
          value: 0
        default_on:
          value: 1
#          type: conditionalValue
          args:
            - isNewValue({id_product}) # condition
            - 1 # value if condition is true
            - null # value if condition is false
        minimal_quantity:
          value: 1
        available_date:
          value: '0000-00-00'

