fields:
    class: 'ProductSupplier'
    unique: 'id_product,id_product_attribute,id_supplier'
    columns:
        id_product:
          relation: Product
          generate_all: true
        id_product_attribute:
          relation: ProductAttribute
        id_supplier:
          relation: Supplier
        product_supplier_reference:
          value: ''
        product_supplier_price_te:
          value: 0