fields:
    class: 'ProductSupplier'
    columns:
        id_product:
          relation: Product
          generate_all: true
        id_currency:
          value: 1
#          relation: Currency
#          generate_all: true
        id_product_attribute:
          relation: ProductAttribute
        id_supplier:
          relation: Supplier
        product_supplier_reference:
          value: ''
        product_supplier_price_te:
          value: 0
